// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYH_XBatwEjqkdnR3znajcxw7N1T4dLZM',
    appId: '1:359438783280:android:0bd711813b7d6081df2ef5',
    messagingSenderId: '359438783280',
    projectId: 'grabsmartly-8287c',
    storageBucket: 'grabsmartly-8287c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE8iLz9iAyKG15Si-tTkrpm_KVm7zxi7Y',
    appId: '1:359438783280:ios:1d80acca3578d1c1df2ef5',
    messagingSenderId: '359438783280',
    projectId: 'grabsmartly-8287c',
    storageBucket: 'grabsmartly-8287c.appspot.com',
    androidClientId: '359438783280-4vhovqsq5adkpf8m9b8rigmf9nao4ov1.apps.googleusercontent.com',
    iosClientId: '359438783280-v18e5807nsejkfbq3i1e6t12013vi3m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.grabsmartly',
  );
}